# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mongoid_slug"
  s.version = "0.4.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hakan Ensari", "Gerhard Lazu"]
  s.date = "2012-04-29"
  s.description = "Mongoid Slug generates a URL slug/permalink based on fields in a Mongoid model."
  s.email = "code@papercavalier.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "lib/mongoid_slug.rb"
  ]
  s.homepage = "http://github.com/papercavalier/mongoid-slug"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Generates a URL slug in a Mongoid model"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, ["= 1.1.3"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<database_cleaner>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, ["= 2.4.9"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.4.9"])
    else
      s.add_dependency(%q<bundler>, ["= 1.1.3"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mongoid>, ["= 2.4.9"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mongoid>, ["~> 2.4.9"])
    end
  else
    s.add_dependency(%q<bundler>, ["= 1.1.3"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mongoid>, ["= 2.4.9"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mongoid>, ["~> 2.4.9"])
  end
end

